# Generated by Django 4.0.4 on 2022-05-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agentname',
            table='agentname',
        ),
    ]
