# Generated by Django 4.0.4 on 2022-05-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_agentname_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentname',
            options={'managed': True},
        ),
    ]
