# Generated by Django 4.0.4 on 2022-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_announcedlgaresults_announcedpuresults_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingunitlgaresult',
            old_name='polling_unit_id',
            new_name='total_lga',
        ),
        migrations.RemoveField(
            model_name='pollingunitlgaresult',
            name='polling_unit_name',
        ),
        migrations.AddField(
            model_name='pollingunitlgaresult',
            name='total_lga_result',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
