# Generated by Django 4.0.4 on 2022-05-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_pollingunitlgaresult_lga_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingunitlgaresult',
            old_name='total_lga',
            new_name='total_lga_polls',
        ),
    ]
