# Generated by Django 4.0.4 on 2022-05-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_rename_total_lga_pollingunitlgaresult_total_lga_polls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcedlgaresults',
            options={'managed': True},
        ),
    ]
