# Generated by Django 3.2.7 on 2022-05-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_alter_announcedlgaresults_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcedlgaresults',
            options={'managed': False},
        ),
    ]
